services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
